db-3187 [next-wordpress] Add Authenticated API to our demo
pantheon-systems/decoupled-kit-js pull request #222
Opened 2022-08-18 14:05 UTC by lotusbaba

## What changes were made?
Added page - examples/auth-api.jsx

## Where were the changes made?
 
 
next-wordpress

## How have the changes been tested?
Yes via localhost

## Additional information

Don't forget to [add a changeset](https://github.com/pantheon-systems/decoupled-kit-js#generating-a-changeset) if needed!

2022-08-18 14:34 UTC, CobyPear requested changes
Some comments mostly re: naming and formatting

2022-08-18 14:34 UTC, CobyPear commented on starters/next-wordpress-starter/pages/examples/auth-api.jsx
> +                <a href="https://github.com/pantheon-systems/decoupled-kit-js/blob/canary/web/docs/Frontend%20Starters/Next%20Wordpress/setting-environment-variables.md">
```suggestion
                <a href="https://github.com/pantheon-systems/decoupled-kit-js/blob/canary/web/docs/Frontend%20Starters/Next.js/Next.js%20%2B%20WordPress/setting-environment-variables.md">
```
This link needs to be updated

2022-08-18 14:34 UTC, CobyPear commented on starters/next-wordpress-starter/pages/examples/auth-api.jsx
> +              to Wordpress! 🎉
```suggestion
              to WordPress! 🎉
```
WP gets mad when you don't capitalize the "P"

2022-08-18 14:34 UTC, CobyPear commented on starters/next-wordpress-starter/pages/examples/auth-api.jsx
> +                WP_APPLICATION_PASSWORD are set correctly.
```suggestion
                ensure that your <code>WP_APPLICATION_USERNAME</code> and
                <code>WP_APPLICATION_PASSWORD</code> are set correctly.
```
Wrap these in code tags to match the formatting of the `next-drupal-starter`

2022-08-18 14:34 UTC, CobyPear commented on starters/next-wordpress-starter/pages/examples/auth-api.jsx
> +                Wordpress API. Please check your .env.development.local file to
```suggestion
                WordPress API. Please check your .env.development.local file to
```

2022-08-18 14:34 UTC, CobyPear commented on starters/next-wordpress-starter/pages/examples/auth-api.jsx
> +  `;
All we really need here is the `id`

2022-08-18 14:34 UTC, CobyPear commented on starters/next-wordpress-starter/pages/examples/auth-api.jsx
> +  }
Let's remove this

2022-08-18 14:34 UTC, CobyPear commented on starters/next-wordpress-starter/pages/examples/auth-api.jsx
> +  const SSRPosts = edges.map(({ node }) => node);
we can be more specific here, maybe call this variable `privatePosts`

2022-08-18 17:51 UTC, CobyPear commented on starters/next-wordpress-starter/pages/examples/auth-api.jsx
> +                <a href="https://github.com/pantheon-systems/decoupled-kit-js/blob/canary/web/docs/Frontend%20Starters/Next%20Wordpress/setting-environment-variables.md">
@lotusbaba this link is still incorrect. See the suggested change

2022-08-18 17:52 UTC, CobyPear requested changes
The link to the doc still seems incorrect, but looks good otherwise!

2022-08-18 19:09 UTC, lotusbaba commented
@CobyPear Resolved your last comment

2022-08-19 13:15 UTC, CobyPear approved these changes
:shipit:

2022-08-19 13:18 UTC, merged