db-3566 [all FE starters] Log helpful message if no env vars are set
pantheon-systems/decoupled-kit-js pull request #224
Opened 2022-08-18 20:30 UTC by lotusbaba

## What changes were made?
Changes to provide meaningful error messages when critical environment variables aren't present

## Where were the changes made?
 
 
Changes to files - `starters/gatsby-wordpress-starter/gatsby-config.js`, `starters/next-wordpress-starter/next.config.js`, & `starters/next-drupal-starter/next.config.js`

## How have the changes been tested?
Yes on http://localhost

## Additional information

Don't forget to [add a changeset](https://github.com/pantheon-systems/decoupled-kit-js#generating-a-changeset) if needed!

2022-08-19 19:06 UTC, CobyPear requested changes
See comments. Also, I don't think the `try/catch` in necessary. If you throw in error in the config it will exit the process appropriately.

2022-08-19 21:48 UTC, lotusbaba commented on starters/next-drupal-starter/next.config.js
> +      "Please set IMAGE_DOMAIN in the .env.development.local file"
Done

2022-08-19 21:48 UTC, lotusbaba commented on starters/gatsby-wordpress-starter/gatsby-config.js
> +  if (!fs.existsSync(path.resolve(process.cwd(), ".env.development.local"))) {
Done

2022-08-22 13:02 UTC, CobyPear requested changes

2022-08-22 13:02 UTC, CobyPear commented on starters/gatsby-wordpress-starter/gatsby-config.js
> +}
The check for the env var looks good, but the error message still doesn't pass the AC on the ticket:

- the error message should suggest ways to fix the problem by checking the NODE_ENV and suggesting an appropriate fix for each 

  - set a .env.development.local with the critical envs for NODE_ENV=development

  - link a backend or set the critical env var in the dashboard for NODE_ENV=production

2022-08-23 19:18 UTC, closed without merging