DB-3787: Refactor block editor support and remove html-react-parser
pantheon-systems/decoupled-kit-js pull request #242
Opened 2022-09-01 16:46 UTC by enZane

## What changes were made?
- Changed the implementation of the post and page rendering
- Removed html-react-parser dependency

## Where were the changes made?
- gatsby-wordpress-starter

## How have the changes been tested?
- locally

## Additional information

Don't forget to [add a changeset](https://github.com/pantheon-systems/decoupled-kit-js#generating-a-changeset) if needed!

2022-09-01 22:16 UTC, CobyPear requested changes
Just one stray console log, LGTM tho, block editor styles seem to be working well!

2022-09-01 22:16 UTC, CobyPear commented on starters/gatsby-wordpress-starter/src/components/post.jsx
> +  console.log({ previous, next })
👀 stray console log?

2022-09-01 22:19 UTC, CobyPear commented
Oh also in this PR, can you update the `package-lock.json` to reflect the removed dependency?

2022-09-01 22:21 UTC, enZane commented on starters/gatsby-wordpress-starter/src/components/post.jsx
> +  console.log({ previous, next })
Oops :p

2022-09-02 12:53 UTC, CobyPear approved these changes

2022-09-02 12:56 UTC, merged