DB-3657: Block Editor Video Styles
pantheon-systems/decoupled-kit-js pull request #326
Opened 2022-10-07 19:28 UTC by mitchellmarkoff

## What changes were made?

- Added button component

## Where were the changes made?
`wordpress-kit`

## How have the changes been tested?
Implemented this component into the next-wordpress-starter locally and tested a sample post with a video to observe expected styles and behavior.

## Additional information

Don't forget to [add a changeset](https://github.com/pantheon-systems/decoupled-kit-js#generating-a-changeset) if needed!

2022-10-10 15:53 UTC, CobyPear requested changes
Seems to be working for an uploaded video, but not an embedded one.
@backlineint would you say that is in scope of this ticket or handled in the future?

2022-10-10 19:00 UTC, mitchellmarkoff commented
> Seems to be working for an uploaded video, but not an embedded one. @backlineint would you say that is in scope of this ticket or handled in the future?

Yeah the way WP seems to handle embedded vs uploaded videos is pretty different. Uploaded videos are put into a `vdieo` tag and given the `wp-block-video `class. Embedded videos are placed into a `div` and not passed the `wp-block-video-class`.

2022-10-10 22:05 UTC, backlineint commented
> > Seems to be working for an uploaded video, but not an embedded one. @backlineint would you say that is in scope of this ticket or handled in the future?
> 
> Yeah WP seems to handle embedded and uploaded videos is pretty differently. Uploaded videos and embedded videos do not share block editor classes.

Wasn't aware that the block editor handled them differently. Unfortunately I think embedded is the more important use case here, so I'd say we should just continue work on this one @mitchellmarkoff

2022-10-13 15:26 UTC, CobyPear requested changes
The block style looks good! Looks like a change for testing got pushed up that needs to be removed.

2022-10-13 16:08 UTC, mitchellmarkoff commented on starters/next-wordpress-starter/tailwind.config.js
> +		extend: { colors: { extend: 'yellow' } },
Yes good catch!

2022-10-13 16:49 UTC, merged