DB-3192: Bubble Up Surrogate Keys On Outgoing Responses
pantheon-systems/decoupled-kit-js pull request #399
Opened 2022-11-16 16:44 UTC by CobyPear

## What changes were made?
- [cms-kit] Move addSurrogateKeyHeader to new cms-kit package
- [wp-kit] Add pantheon-debug header to wp-kit graphql client outgoing requests
- [next-wp] Refactor data fetchers to return headers
- [next-wp] Combine headers and add them to res in getServerSideProps using addSurrogateKeyHeader
- [next-wp] Add helper to get unique keys from multiple surrogate-key-raw headers

## Where were the changes made?
new cms-kit, wp-kit, drupal-kit, and next-wp-starter

## How have the changes been tested?
Tests written as needed
## Additional information

Don't forget to [add a changeset](https://github.com/pantheon-systems/decoupled-kit-js#generating-a-changeset) if needed!

2022-11-20 19:02 UTC, backlineint requested changes
Working well - just a few minor things and questions. In addition to what is included inline:

* For a site that does not have the pantheon-advanced-page-cache activated, the Surrogate-Key-Raw header is set, but it is empty. In that case, I'd expect the header to not be set at all.

2022-11-21 14:36 UTC, CobyPear commented on packages/wordpress-kit/index.ts
> +export { gql, addSurrogateKeyHeader };
No good reason, it should be exported from both :) Change incoming.

2022-11-21 14:47 UTC, CobyPear commented on starters/next-wordpress-starter/pages/index.jsx
> +	setEdgeHeader({ res });
Yeah that makes sense to me. So I would essentially be combining these operations into one function?

Related, I propose we decide on "add" or "set" and refactor accordingly. I'm not a huge fan of using both as it's a bit confuisng. Which do you think we should use?

2022-11-21 20:11 UTC, backlineint commented on starters/next-wordpress-starter/pages/index.jsx
> +	setEdgeHeader({ res });
Saw that you landed on set - I think that makes sense.

2022-11-21 20:18 UTC, backlineint approved these changes

2022-11-21 20:18 UTC, merged