DB-5713: Search Term Persistence
pantheon-systems/decoupled-kit-js pull request #608
Opened 2023-04-04 13:48 UTC by mitchellmarkoff

## What changes were made?
- The search term entered into the header persists on the search results page.

## Where were the changes made?
`cli > templates > next-drupal-search-api-addon`

## How have the changes been tested?
Search term observed to persist during local development.

## Additional information
As mentioned in the ticket this state persistence needed to be 'faked' since we have two `SearchInput` components, one in `/pages` and one in `/app` 

Don't forget to [add a changeset](https://github.com/pantheon-systems/decoupled-kit-js#generating-a-changeset) if needed!

2023-04-04 15:10 UTC, CobyPear requested changes
This seems to be working fine if I remove the catchall route, otherwise when I try to search for a query I see "No content found 🏜️"

2023-04-06 19:58 UTC, mitchellmarkoff commented
Made this a minor bump because this PR does add SOME functionality. However, since this is a very small amount of work I could see a case for this to be a patch.

2023-04-11 13:43 UTC, CobyPear requested changes
LGTM, just one small change requested on the changeset.

2023-04-11 13:43 UTC, CobyPear commented on .changeset/swift-dogs-care.md
> +[next-drupal] User entered search term persists on search results page in the
```suggestion
[next-drupal-search-api-addon] User entered search term persists on search results page in the
```
More specificity with the tag here so we can easily tell which generators were changed at a glance of the changelog

2023-04-11 14:03 UTC, CobyPear approved these changes

2023-04-11 14:03 UTC, merged